#!/bin/bash
# To Do:
#  check required dependencies
#
if [ -z "$1" ]; then
        echo "";echo "Usage: `basename $0` [URL]";echo "";
        exit
fi

read -r -p "Would you like the .mp3 file saved to your Music folder? (Alternatively, it will be saved in the current working directory) [y/n] " response
case $response in
    [yY][eE][sS]|[yY]) 
        saveDir="~/Music" 
        ;;
    *)
        saveDir="." 
        ;;
esac

echo "[+] Downloading video, extracting audio, and removing video file"
youtube-dl -x --audio-format mp3 --audio-quality 128K --exec "mv {} $saveDir/mp3.mp3" "$1"

echo "[+] Enter song information for the audio file: "
echo -n "[?] Artist name: "
read -e ARTIST
id3v2 -a "$ARTIST" $saveDir/mp3.mp3

echo -n "[?] Track title: "
read -e TITLE
id3v2 -t "$TITLE" $saveDir/mp3.mp3

mv $saveDir/mp3.mp3 "$ARTIST - $TITLE.mp3"

echo "[!] All done! Enjoy '$ARTIST - $TITLE.mp3'"
echo "[!] Thanks for using Rolle's shitty script!"
