#!/bin/bash
# To Do:
#  check required dependencies
#
if [ -z "$1" ]; then
        echo "";echo "Usage: `basename $0` [URL]";echo "";
        exit
fi

read -r -p "Would you like the .mp3 file saved to your Music folder? (Alternatively, it will be saved in the current working directory) [y/n] " response
case $response in
    [yY][eE][sS]|[yY]) 
        saveDir="~/Music" 
        ;;
    *)
        saveDir="." 
        ;;
esac

echo "[+] Enter song information for the audio file: "
echo -n "[?] Artist name: "
read -e ARTIST
echo -n "[?] Track title: "
read -e TITLE
FILENAME="$ARTIST - $TITLE.mp3"

echo "[+] Downloading video, extracting audio, and deleting video file"
youtube-dl -x --audio-format mp3 --audio-quality 128K --exec "mv {} \"$saveDir/$FILENAME\"" "$1"

id3v2 -a "$ARTIST" "$saveDir/$FILENAME"
id3v2 -t "$TITLE" "$saveDir/$FILENAME"

echo "[!] All done! Enjoy $FILENAME"
echo "[!] Thanks for using Rolle's shitty script!"
